name: Build the TS SDK upload to S3, and invalidate cloudFront cache

on:
    push:
        branches:
            - main
        # paths:
        #     - packages/js/**

jobs:
    build-upload-invalidate:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 14

            - name: Install Dependencies
              run: yarn install

            - name: Build SDK
              run: yarn workspace @revertdotdev/js build
              env:
                  CORE_API_BASE_URL: ${{ secrets.CORE_API_BASE_URL }}
                  REDIRECT_URL_BASE: ${{ secrets.REDIRECT_URL_BASE }}
            - name: List Files in Workspace
              run: ls -R
            - name: Upload bundle to S3
              uses: jakejarvis/s3-sync-action@master
              with:
                  args: --acl public-read --follow-symlinks --delete
              env:
                  AWS_S3_BUCKET: cdn.revert.dev
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  SOURCE_DIR: /home/runner/work/Revert/Revert/packages/js/build/revert.js

            - name: Invalidate CloudFront Cache
              run: |
                  aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws configure set default.region ${{ secrets.AWS_REGION }}
                  aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/*"
